 components:
      schemas:
          createProduct:
              type : object
              required : 
                  -    title
                  -    short_text
                  -    text
                  -    price
                  -    count
                  -    features
                  -    tags
                  -    category
              properties:
                  title:
                      type : string
                      description : title for product
                  short_text:
                      type : string
                      description : short description for product
                  text:
                      type : string
                      description : description for product
                  price:
                      type : number
                      description : product's price
                  discount:
                      type : number
                      description : product's descount
                  count:
                      type : number
                      description : total count of product
                  category:
                      type : string
                      description : category of product
                  features:
                      type : object
                      description : length/width/height/weigth/model/madein  of product
                      properties:
                          length:
                              type : number
                              description : CM
                          width:
                              type : number
                              description : CM
                          height:
                              type : number
                              description : CM
                          weight:
                              type : number
                              description : g
                          model:
                              type : string
                          madein:
                              type : string
                  tags:
                      type : array
                      description : tags for product
                      items:
                          type : string
                  images:
                      type : array
                      items:
                          type : string
                          format : binary
          editProduct:
              type : object
              properties:
                  title:
                      type : string
                      description : title for product
                  short_text:
                      type : string
                      description : short description for product
                  text:
                      type : string
                      description : description for product
                  price:
                      type : number
                      description : product's price
                  discount:
                      type : number
                      description : product's descount
                  count:
                      type : number
                      description : total count of product
                  features:
                      type : object
                      description : length/width/height/weigth/model/madein  of product
                      properties:
                          length:
                              type : number
                              description : CM
                          width:
                              type : number
                              description : CM
                          height:
                              type : number
                              description : CM
                          weight:
                              type : number
                              description : g
                          model:
                              type : string
                          madein:
                              type : string
                  tags:
                      type : array
                      description : tags for product
                      items:
                          type : string
                  category:
                      type : string
                      description : category of product
                  images:
                      type : array
                      items:
                          type : string
                          format : binary


 /admin/product/create:
      post:
          tags : [product]
          summary : create new product
          description : create new product
          requestBody:
              required : true
              content:
                  multipart/form-data:
                      schema:
                          $ref : '#/components/schemas/createProduct'

          security:
              -   bearerAuth : []
          responses:
              201:
                  description : successfull
                  content:
                      application/json:
                          schema:
                              $ref: '#/definitions/createProductResponse'






 /admin/product/edit/{productId}:
      patch:
          tags : [product]
          summary : edit product
          description : edit product with product id
          parameters:
              -   in : path
                  type : string
                  name : productId 
                  required : true
          requestBody:
              required : true
              content:
                  multipart/form-data:
                      schema:
                          $ref : '#/components/schemas/editProduct'

          security:
              -   bearerAuth : []
          responses:
              201:
                  description : successfull
                  content:
                      application/json:
                          schema:
                              $ref: '#/definitions/response'





 /admin/product/delete/{productId}:
      delete :
          tags : [product]
          summary : delete product
          description : delete product with product id
          security :
              -   bearerAuth : []
          parameters : 
              -   in : path
                  name : productId
                  type : string
                  required : true
          responses : 
              200 :
                  description : successfull
                  content:
                      application/json:
                          schema:
                              $ref: '#/definitions/response'

